name: Sync Fork with Upstream (Keep Workflows)

on:
  schedule:
    - cron: '0 0 * * *' # 每天同步一次
  workflow_dispatch:
    inputs:
      upstream_repo:
        description: '上游仓库地址 (例如 https://github.com/luongz/iptv-jp.git)'
        required: true
        default: 'https://github.com/luongz/iptv-jp.git'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ 检出仓库
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      # 2️⃣ 先备份 workflow 文件
      - name: Backup workflows
        run: |
          mkdir -p /tmp/myworkflows
          cp -r .github/workflows/* /tmp/myworkflows/ || echo "No workflows to backup"

      # 3️⃣ 配置 Git 用户
      - name: Set up Git
        run: |
          git config --global user.name "chzw2025"
          git config --global user.email "194056861+chzw2025@users.noreply.github.com"

      # 4️⃣ 添加上游仓库并拉取
      - name: Add upstream
        run: |
          git remote add upstream ${{ github.event.inputs.upstream_repo }}
          git fetch upstream

      # 5️⃣ 获取默认分支
      - name: Get default branch
        id: vars
        run: echo "DEFAULT_BRANCH=$(git remote show origin | grep 'HEAD branch' | cut -d':' -f2 | tr -d ' ')" >> $GITHUB_ENV

      # 6️⃣ Merge 上游内容
      - name: Merge upstream
        run: |
          git checkout $DEFAULT_BRANCH
          git merge upstream/$DEFAULT_BRANCH --allow-unrelated-histories || echo "Merge finished"

      # 7️⃣ 恢复自己备份的 workflow 文件
      - name: Restore workflows
        run: |
          cp -r /tmp/myworkflows/* .github/workflows/ || echo "No workflows to restore"
          git add .github/workflows

      # 8️⃣ 提交并推送
      - name: Push changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git
          git commit -m "Sync with upstream, keep own workflows" || echo "No changes to commit"
          git push origin $DEFAULT_BRANCH --force
