name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # 每天 0 点自动运行
  workflow_dispatch:
    inputs:
      upstream_repo:
        description: '上游仓库地址 (例如 https://github.com/iptv-org/iptv.git)'
        required: false
        default: 'https://github.com/iptv-org/iptv.git'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "chzw2025"
          git config --global user.email "194056861+chzw2025@users.noreply.github.com"

      - name: Add upstream
        run: |
          # 如果手动触发传入参数，就用输入值，否则用默认值
          UPSTREAM_REPO="${{ github.event.inputs.upstream_repo }}"
          if [ -z "$UPSTREAM_REPO" ]; then
            UPSTREAM_REPO="https://github.com/iptv-org/iptv.git"
          fi
          echo "Using upstream repo: $UPSTREAM_REPO"
          git remote add upstream "$UPSTREAM_REPO"

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main || git checkout master
          git merge upstream/main --allow-unrelated-histories || true

          # 恢复 workflows 文件夹，防止被覆盖
          git checkout HEAD -- .github/workflows || true

      - name: Push changes
        run: |
          git push origin HEAD
